In [1]:
pip install webdriver-manager

Requirement already satisfied: webdriver-manager in c:\users\ashu\anaconda3\lib\site-packages (3.8.4)Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: tqdm in c:\users\ashu\anaconda3\lib\site-packages (from webdriver-manager) (4.64.0)
Requirement already satisfied: requests in c:\users\ashu\anaconda3\lib\site-packages (from webdriver-manager) (2.27.1)
Requirement already satisfied: python-dotenv in c:\users\ashu\anaconda3\lib\site-packages (from webdriver-manager) (0.21.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ashu\anaconda3\lib\site-packages (from requests->webdriver-manager) (2021.10.8)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ashu\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\ashu\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\ashu\anaconda3\lib\site-packages (from requests->webdriver-manager) (1.26.9)
Requirement already satisfied: colorama in c:\users\ashu\anaconda3\lib\site-packages (from tqdm->webdriver-manager) (0.4.4)

In [4]:
# import necessary libraries at once

import pandas as pd
import selenium
import time
from bs4 import BeautifulSoup 
from selenium import webdriver
from selenium.webdriver.common.by import By

from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
import requests
from webdriver_manager.chrome import ChromeDriverManager
import re
from selenium.webdriver.support.ui import WebDriverWait
import warnings
warnings.filterwarnings('ignore')

# 1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos

You need to find following details:

 1.Rank 2. Name 3. Artist 4. Upload date 5.View

In [58]:
driver = webdriver.Chrome(ChromeDriverManager().install())

# Getting the webpage of url 

url=("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [59]:
# Creating empty list for storing data after scraping

Rank = []
Name = []
Artist = []
UploadDate = []
Views = []

# Scraping Rank of the videos
try:
    for i in driver.find_elements(By.XPATH,"/html/body/div[3]/div[3]/div[5]/div[1]/table[2]/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")

#scrapping name
try:
    for i in driver.find_elements(By.XPATH,"/html/body/div[3]/div[3]/div[5]/div[1]/table[2]/tbody/tr/td[2]"):
        Name.append(i.text)
except NoSuchElementException:
    Name.append("_")
    
    
#scrapping Artist
try:
    for i in driver.find_elements(By.XPATH,'/html/body/div[3]/div[3]/div[5]/div[1]/table[2]/tbody/tr/td[3]'):
        Artist.append(i.text)
except NoSuchElementException:
    Artist.append("_")
    
    
#Scrapping Upload Date
try:
    for i in driver.find_elements(By.XPATH,' /html/body/div[3]/div[3]/div[5]/div[1]/table[2]/tbody/tr/td[5]'):
        UploadDate.append(i.text)
except NoSuchElementException:
    UploadDate.append('-')

    
# Scraping Views of videos
try:
    for i in driver.find_elements(By.XPATH,"/html/body/div[3]/div[3]/div[5]/div[1]/table[2]/tbody/tr/td[4]"):
        Views.append(i.text)
except NoSuchElementException:
    Views.append("_")

In [60]:
# Creating DataFrame from scraped data
wikipedia = pd.DataFrame({})
wikipedia['Rank']=Rank
wikipedia['Name']=Name
wikipedia['Artist']=Artist
wikipedia['Upload Date']=UploadDate
wikipedia['Views']=Views

In [61]:
wikipedia

,Rank,Name,Artist,Upload Date,Views
0,1.,"""Baby Shark Dance""[4]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",11.83
1,2.,"""Despacito""[7]",Luis Fonsi,"January 12, 2017",8.02
2,3.,"""Johny Johny Yes Papa""[14]",LooLoo Kids,"October 8, 2016",6.54
3,4.,"""Shape of You""[15]",Ed Sheeran,"January 30, 2017",5.86
4,5.,"""Bath Song""[17]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.81
5,6.,"""See You Again""[18]",Wiz Khalifa,"April 6, 2015",5.71
6,7.,"""Phonics Song with Two Words""[23]",ChuChu TV,"March 6, 2014",5.04
7,8.,"""Uptown Funk""[24]",Mark Ronson,"November 19, 2014",4.77
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[25]",Miroshka TV,"February 27, 2018",4.74
9,10.,"""Wheels on the Bus""[26]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.69
10,11.,"""Gangnam Style""[27]",Psy,"July 15, 2012",4.62
11,12.,"""Masha and the Bear – Recipe for Disaster""[32]",Get Movies,"January 31, 2012",4.52
12,13.,"""Dame Tu Cosita""[33]",El Chombo,"April 5, 2018",4.15
13,14.,"""Sugar""[34]",Maroon 5,"January 14, 2015",3.79
14,15.,"""Roar""[35]",Katy Perry,"September 5, 2013",3.69
15,16.,"""Counting Stars""[36]",OneRepublic,"May 31, 2013",3.69
16,17.,"""Axel F""[37]",Crazy Frog,"June 16, 2009",3.63
17,18.,"""Sorry""[38]",Justin Bieber,"October 22, 2015",3.61
18,19.,"""Thinking Out Loud""[39]",Ed Sheeran,"October 7, 2014",3.52
19,20.,"""Baa Baa Black Sheep""[40]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.44
20,21.,"""Dark Horse""[41]",Katy Perry,"February 20, 2014",3.40
21,22.,"""Faded""[42]",Alan Walker,"December 3, 2015",3.38
22,23.,"""Girls Like You""[43]",Maroon 5,"May 31, 2018",3.35
23,24.,"""Let Her Go""[44]",Passenger,"July 25, 2012",3.35
24,25.,"""Waka Waka (This Time for Africa)""[45]",Shakira,"June 4, 2010",3.34
25,26.,"""Perfect""[46]",Ed Sheeran,"November 9, 2017",3.31
26,27.,"""Bailando""[47]",Enrique Iglesias,"April 11, 2014",3.30
27,28.,"""Lean On""[48]",Major Lazer,"March 22, 2015",3.29
28,29.,"""Humpty the train on a fruits ride""[49]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.24
29,30.,"""Shake It Off""[50]",Taylor Swift,"August 18, 2014",3.23

In [62]:
driver.close()

# 2. Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.

You need to find following details: 1) Match title  2) Series 3) Place 4) Date 5) Time

In [23]:

driver = webdriver.Chrome(ChromeDriverManager().install())
# Getting the webpage of mentioned url 
url=('https://www.bcci.tv/')
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [24]:
#clickin on International tab
International = driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a') # click button
International.click()

In [25]:
#Creating Empty List
Name=[]
Series=[]
Place=[]
Date=[]
Time=[]

#Scrapping Name
try:
    for i in driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]'):
        Name.append(i.text.replace('-',""))
except NoSuchElementException:
    Name.append('-')

#Scrapping Series
try:
     for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding"]'):
        Series.append(i.text)
except NoSuchElementException:
    Series.append('-')

#scrapping Place
try:
    for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]'):
        Place.append(i.text)
except NoSuchElementException:
    Place.append('-')

#Scrapping Date
try:
    for i in driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]'):
        Date.append(i.text)
except NoSuchElementException:
    Date.append('-')

#Scrapping Time
try:
    for i in driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]'):
        Time.append(i.text.replace('IST',""))
except NoSuchElementException:
    Time.append('-')

In [26]:
# Create Dataframe

Fixtures=pd.DataFrame({})
Fixtures['Title']=Series
Fixtures['Name']=Name
Fixtures['Place']=Place
Fixtures['Date']=Date
Fixtures['Time']=Time
Fixtures

,Title,Name,Place,Date,Time
0,AUSTRALIA WOMEN TOUR OF INDIA 2022,2nd T20I,"DY Patil Stadium,",11 DEC 2022,7:00 PM
1,INDIA TOUR OF BANGLADESH TEST SERIES 2022-23,1st Test,"Zahur Ahmed Chowdhury Stadium,",14 DEC 2022,9:30 AM
2,AUSTRALIA WOMEN TOUR OF INDIA 2022,3rd T20I,"Brabourne - CCI,",14 DEC 2022,7:00 PM
3,AUSTRALIA WOMEN TOUR OF INDIA 2022,4th T20I,"Brabourne - CCI,",17 DEC 2022,7:00 PM
4,AUSTRALIA WOMEN TOUR OF INDIA 2022,5th T20I,"Brabourne - CCI,",20 DEC 2022,7:00 PM
5,INDIA TOUR OF BANGLADESH TEST SERIES 2022-23,2nd Test,"Shere Bangla National Stadium, Mirpur,",22 DEC 2022,9:30 AM
6,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,1st T20I,"Wankhede Stadium,",3 JAN 2023,7:30 PM
7,SRI LANKA TOUR OF INDIA T20 SERIES 2022-23,2nd T20I,"Maharashtra Cricket Association Stadium,",5 JAN 2023,7:30 PM

In [27]:
driver.close()

# 3. Scrape the details of selenium exception from guru99.com.
Url = https://www.guru99.com/

You need to find following details: A) Name B) Description

In [44]:
driver = webdriver.Chrome(ChromeDriverManager().install())
# Getting the webpage of mentioned url 
url=('https://www.guru99.com/')
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [45]:
# Click Selenium Button
Selenium = driver.find_element(By.XPATH,'//div[@class = "wp-block-kadence-column inner-column-2 kadence-column_f38d98-3a"]') 
# click button
try:
    Selenium.click()
except ElementNotInteractableException:   
    #handling element not clickable exception
    driver.get(Selenium.get_attribute('href'))
time.sleep(3)

In [46]:
# Click selenium exception handling  Button
exception_handling = driver.find_element(By.XPATH,"//a[@title='Selenium Exception Handling (Common Exceptions List)']")
try:
    exception_handling.click()
except ElementNotInteractableException: 
#if the above code doesn't work/is not clickable then, the below code will handle it
    driver.get(exception_handling.get_attribute('href'))

In [47]:
name=[]
desc=[]
#Scrapping Name
for i in driver.find_elements(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div/p/strong'):
    name.append(i.text)
for i in driver.find_elements(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div/p'):
    desc.append(i.text)

In [48]:
Selenium_Exception=pd.DataFrame()
Selenium_Exception['Exception name']=name[0:41]
Selenium_Exception['Description']=desc[0:41]
Selenium_Exception

,Exception name,Description
0,1. ElementNotVisibleException:,1. ElementNotVisibleException: This type of Se...
1,2. ElementNotSelectableException:,2. ElementNotSelectableException: This Seleniu...
2,3. NoSuchElementException:,3. NoSuchElementException: This Exception occu...
3,4. NoSuchFrameException:,4. NoSuchFrameException: This Exception occurs...
4,5. NoAlertPresentException:,5. NoAlertPresentException: This Exception occ...
5,6. NoSuchWindowException:,6. NoSuchWindowException: This Exception occur...
6,7. StaleElementReferenceException:,7. StaleElementReferenceException: This Seleni...
7,8. SessionNotFoundException:,8. SessionNotFoundException: The WebDriver is ...
8,9. TimeoutException:,9. TimeoutException: Thrown when there is not ...
9,10. WebDriverException:,10. WebDriverException: This Exception takes p...
10,11. ConnectionClosedException:,11. ConnectionClosedException: This type of Ex...
11,12. ElementClickInterceptedException:,12. ElementClickInterceptedException: The comm...
12,13. ElementNotInteractableException:,13. ElementNotInteractableException: This Sele...
13,14. ErrorInResponseException:,14. ErrorInResponseException: This happens whi...
14,15. ErrorHandler.UnknownServerException:,15. ErrorHandler.UnknownServerException: Excep...
15,16. ImeActivationFailedException:,16. ImeActivationFailedException: This expecta...
16,17. ImeNotAvailableException:,17. ImeNotAvailableException: It takes place w...
17,18. InsecureCertificateException:,18. InsecureCertificateException: Navigation m...
18,19. InvalidArgumentException:,19. InvalidArgumentException: It occurs when a...
19,20. InvalidCookieDomainException:,20. InvalidCookieDomainException: This happens...
20,21. InvalidCoordinatesException:,21. InvalidCoordinatesException: This type of ...
21,22. InvalidElementStateException:,22. InvalidElementStateException: It occurs wh...
22,23. InvalidSessionIdException:,23. InvalidSessionIdException: This Exception ...
23,24. InvalidSwitchToTargetException:,24. InvalidSwitchToTargetException: This occur...
24,25. JavascriptException:,25. JavascriptException: This issue occurs whi...
25,26. JsonException:,26. JsonException: It occurs when you afford t...
26,27. NoSuchAttributeException:,27. NoSuchAttributeException: This kind of Exc...
27,28. MoveTargetOutOfBoundsException:,28. MoveTargetOutOfBoundsException: It takes p...
28,29. NoSuchContextException:,29. NoSuchContextException: ContextAware does ...
29,30. NoSuchCookieException:,30. NoSuchCookieException: This Exception occu...
30,31. NotFoundException:,31. NotFoundException: This Exception is a sub...
31,32. RemoteDriverServerException:,32. RemoteDriverServerException: This Selenium...
32,33. ScreenshotException:,33. ScreenshotException: It is not possible to...
33,34. SessionNotCreatedException:,34. SessionNotCreatedException: It happens whe...
34,35. UnableToSetCookieException:,35. UnableToSetCookieException: This occurs if...
35,36. UnexpectedTagNameException:,36. UnexpectedTagNameException: Happens if a s...
36,37. UnhandledAlertException:,37. UnhandledAlertException: This expectation ...
37,38. UnexpectedAlertPresentException:,38. UnexpectedAlertPresentException: It occurs...
38,39. UnknownMethodException:,39. UnknownMethodException: This Exception hap...
39,40. UnreachableBrowserException:,40. UnreachableBrowserException: This Exceptio...
40,41. UnsupportedCommandException:,41. UnsupportedCommandException: This occurs w...

In [49]:
driver.close()

# 4. Scrape the details of State-wise GDP of India from statisticstime.com.
Url = http://statisticstimes.com/

You have to find following details: 1) Rank 2) State 3) GSDP(18-19) 4) GSDP(17-18) 5) Share(2017) 6) GDP($ billion)

In [50]:
driver = webdriver.Chrome(ChromeDriverManager().install())

# Getting the webpage of mentioned url 
url=(' http://statisticstimes.com/ ')
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [51]:
driver.find_element(By.XPATH,'/html/body/div[1]/div/a').click()

In [52]:
#Clicking on Economy button
driver.find_element(By.XPATH,"//div[@class='navbar']/div[2]/button").click()

In [53]:
#Clicking on India
exception_handling=driver.find_element(By.XPATH,"//div[@class='dropdown-content']/a[3]")
try:
    exception_handling.click()
except ElementNotInteractableException: 
    driver.get(exception_handling.get_attribute('href'))

In [54]:
# Clicking on GDP of Indian Economy
GDP = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a').click()
time.sleep(3)

In [55]:
# Creating empty list
Rank = []
State = []
GSDP2 = []
Share = []
GDPbillion = []
# Scraping Rank
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
# Scraping State
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException:
    State.append("_")
# Scraping GSDP at current price (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException:
    GSDP2.append("_")
# Scraping Share (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException:
    Share.append("_")
# Scraping GDP $ billion
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDPbillion.append(i.text)
except NoSuchElementException:
    GDPbillion.append("_")

In [56]:
INDIA=pd.DataFrame()
INDIA['RANK']=Rank
INDIA['STATE']=State
INDIA['GSDP2']=GSDP2
INDIA['SHARE']=Share
INDIA['GDPbillion']=GDPbillion
INDIA

   RANK                      STATE      GSDP2   SHARE GDPbillion
0     1                Maharashtra  2,632,792  13.94%    399.921
1     2                 Tamil Nadu  1,630,208   8.63%    247.629
2     3              Uttar Pradesh  1,584,764   8.39%    240.726
3     4                    Gujarat  1,502,899   7.96%    228.290
4     5                  Karnataka  1,493,127   7.91%    226.806
..  ...                        ...        ...     ...        ...
61   29                     Sikkim     25,141   0.15%     17,060
62   30                   Nagaland     24,534   0.15%          -
63   31          Arunachal Pradesh     22,488   0.13%          -
64   32                    Mizoram     20,947   0.13%     17,797
65   33  Andaman & Nicobar Islands          -       -          -

[66 rows x 5 columns]

In [57]:
driver.close()

# 5. Scrape the details of trending repositories on Github.com.
Url = https://github.com/

You have to find the following details: 1) Repository title 2) Repository description 3) Contributors count 4) Language use

In [28]:
driver = webdriver.Chrome(ChromeDriverManager().install())
# Getting the webpage of mentioned url 
url=('https://github.com/explore')
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [29]:
# Click on explore

explore = driver.find_element(By.XPATH,'/html/body/div[4]/main/div[1]/nav/div/a[1]')
try:
    explore.click()
    time.sleep(5)
except ElementNotInteractableException:
    driver.get(explore.get_attribute('href'))

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[4]/main/div[1]/nav/div/a[1]"}
  (Session info: chrome=108.0.5359.94)
Stacktrace:
Backtrace:
	(No symbol) [0x0073F243]
	(No symbol) [0x006C7FD1]
	(No symbol) [0x005BD04D]
	(No symbol) [0x005EC0B0]
	(No symbol) [0x005EC22B]
	(No symbol) [0x0061E612]
	(No symbol) [0x006085D4]
	(No symbol) [0x0061C9EB]
	(No symbol) [0x00608386]
	(No symbol) [0x005E163C]
	(No symbol) [0x005E269D]
	GetHandleVerifier [0x009D9A22+2655074]
	GetHandleVerifier [0x009CCA24+2601828]
	GetHandleVerifier [0x007E8C0A+619850]
	GetHandleVerifier [0x007E7830+614768]
	(No symbol) [0x006D05FC]
	(No symbol) [0x006D5968]
	(No symbol) [0x006D5A55]
	(No symbol) [0x006E051B]
	BaseThreadInitThunk [0x76536939+25]
	RtlGetFullPathName_UEx [0x77848FD2+1218]
	RtlGetFullPathName_UEx [0x77848F9D+1165]

In [30]:
# Click on Trending

trending = driver.find_element(By.XPATH,'//*[@href="/trending"]')
try:
    driver.get(trending.get_attribute('href'))
except ElementNotInteractableException:
    driver.get(trending.get_attribute('href'))

In [31]:
#Creating empty list:
URLs = []
repository_title = []
Description = []
Contributors = []
Language = []
lang = []

#Fetching urls for each repository
repository = driver.find_elements(By.XPATH,"//h1[@class = 'h3 lh-condensed']//a")
for i in repository:
    URLs.append(i.get_attribute("href"))

In [32]:
# Scraping Repository Title data
title = driver.find_elements(By.XPATH,"//h1[@class = 'h3 lh-condensed']")
for i in title:
    repository_title.append(i.text)

In [33]:
# Scraping data from all repository page
for i in URLs:
    driver.get(i)
    time.sleep(2)
    
        # Scraping Repository Description data
    try:
        desc = driver.find_element(By.XPATH,"//p[@class='f4 my-3']")
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        
    # Scraping Contributors Count data
    try:
        contributor = driver.find_element(By.XPATH,"//*[contains(text(),'    Contributors ')]")
        Contributors.append(contributor.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
        
        
     # Scraping Languages used data
    lang=[]
    try:
        for i in driver.find_elements(By.XPATH,'//span[@class="color-fg-default text-bold mr-1"]'):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        lang.append('-')

In [34]:
print(len(repository_title),len(Description),len(Contributors),len(Language))

25 25 25 25

In [35]:
#Data Frame

Github=pd.DataFrame({})
Github['Repository title'] = repository_title
Github['Repository description'] = Description
Github['Contributors count'] = Contributors
Github['Language used'] = Language
Github

,Repository title,Repository description,Contributors count,Language used
0,fuergaosi233 / wechat-chatgpt,Use ChatGPT On Wechat via wechaty,21,"[TypeScript, Python, Dockerfile, Shell]"
1,869413421 / wechatbot,为个人微信接入ChatGPT,4,"[Go, Dockerfile, Makefile]"
2,exaloop / codon,"A high-performance, zero-overhead, extensible ...",4,"[C++, Python, Other]"
3,doocs / leetcode,😏 LeetCode solutions in any programming langua...,108,"[Java, C++, Python, Go, TypeScript, Rust, Other]"
4,teaxyz / cli,the unified package manager (brew2),17,[TypeScript]
5,Tencent / Hippy,Hippy is designed to easily build cross-platfo...,80,"[C++, Java, Objective-C, TypeScript, JavaScrip..."
6,cloneofsimo / lora,Using Low-rank adaptation to quickly fine-tune...,2,"[Jupyter Notebook, Other]"
7,AutumnWhj / ChatGPT-wechat-bot,ChatGPT for wechat,2,"[TypeScript, JavaScript, Dockerfile, Shell]"
8,PathOfBuildingCommunity / PathOfBuilding,Offline build planner for Path of Exile.,187,[Lua]
9,surrealdb / surrealdb,"A scalable, distributed, collaborative, docume...",31,"[Rust, Other]"
10,gragland / chatgpt-chrome-extension,A ChatGPT Chrome extension. Integrates ChatGPT...,-,"[JavaScript, Shell]"
11,wangrongding / wechat-bot,🤖一个基于OpenAi ChatGPT + WeChaty 实现的微信机器人 可以用来帮助你...,2,"[JavaScript, Shell]"
12,mohammadpz / pytorch_forward_forward,Implementation of Hinton's forward-forward (FF...,2,[Python]
13,holbertonschool / Betty,Holberton-style C code checker written in Perl,8,"[Perl, C, Shell]"
14,humanloop / awesome-chatgpt,"Curated list of awesome tools, demos, docs for...",5,[]
15,rawandahmad698 / PyChatGPT,⚡️ Python client for the unofficial ChatGPT AP...,9,[Python]
16,pulsar-edit / pulsar,A Community-led Hyper-Hackable Text Editor,487,"[JavaScript, CoffeeScript, Less, Ruby, Shell, ..."
17,bupticybee / ChineseAiDungeonChatGPT,中文版的ai地牢，直接使用的openai的ChatGPT api作为讲故事的模型。,3,"[Python, Jupyter Notebook]"
18,f / awesome-chatgpt-prompts,This repo includes ChatGPT promt curation to u...,10,[]
19,louislam / uptime-kuma,A fancy self-hosted monitoring tool,209,"[JavaScript, Vue, SCSS, TypeScript, Shell, Doc..."
20,pichenettes / eurorack,Eurorack modules,11,"[C++, Python, Other]"
21,acheong08 / ChatGPT,Lightweight package for interacting with ChatG...,24,[Python]
22,paradigmxyz / reth,"Modular, contributor-friendly and blazing-fast...",13,"[C, Rust, C++, CMake, Other]"
23,bytedance / sonic-cpp,A fast JSON serializing & deserializing librar...,3,"[C++, Python, CMake, Other]"
24,AmazingAng / WTF-Solidity,我最近在重新学solidity，巩固一下细节，也写一个“WTF Solidity极简入门”，...,70,"[Solidity, JavaScript]"

In [67]:
driver.close()

# 6. Scrap the details of top 100 songs on billiboard.com.
Url = https:/www.billboard.com/

You have to find the following details: 1) Song name 2) Artist name 3) Last week rank 4) Peak rank 5) Weeks on board

In [45]:
driver = webdriver.Chrome(ChromeDriverManager().install())

# Getting the webpage of mentioned url 
url=('https:/www.billboard.com/')
    
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [46]:
# Clicking on button tab

button =driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a')
driver.get(button.get_attribute('href'))
time.sleep(2)

In [47]:
# Clicking on hot100 tab

hot100 =driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[3]/div/nav/ul/li[1]/a')
driver.get(hot100.get_attribute('href'))
time.sleep(2)

In [48]:
# Creating Empty List for scrapped datas

name =[]
artist =[]
rank=[]
peak_rank =[]
weeks =[]
all_info=[]

In [49]:
# Scraping Song Name
try:
    song_tags =driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li/h3')
    for i in song_tags:
        name.append(i.text)
except NoSuchElementException:
    name.append('NA')

In [50]:
len(name)

0

In [51]:
all_info=[]
try:
    all_tags =driver.find_elements(By.XPATH,'//ul[@class="lrv-a-unstyle-list lrv-u-flex lrv-u-height-100p lrv-u-flex-direction-column@mobile-max"]/li/span')
    for i in all_tags:
        all_info.append(i.text)
except NoSuchElementException:
    all_info.append('NA')

In [52]:
# Scraping artist
artist= all_info[0:401:4]
len(artist)

0

In [53]:
# Scraping rank
rank= all_info[1:401:4]
len(rank)

0

In [54]:
# Scraping rank
peak_rank= all_info[2:401:4]
len(peak_rank)

0

In [55]:
# Scraping weeks
weeks= all_info[3:401:4]
len(weeks)

0

In [56]:
# Creating DataFrame for scrapped data

data_list= list(zip(name,artist,rank,peak_rank,weeks ))

data= pd.DataFrame(data_list, 
    columns =['Song_name', 'Artist_name', 'Last_week_rank','Peak_rank','Weeks on board'],
                  index=pd.RangeIndex(start=1, stop=101, name='This_week_rank'))

#Print the required data

print ("Details of top 100 songs on billiboard.com.:\n")
data

Details of top 100 songs on billiboard.com.:

               Song_name Artist_name Last_week_rank Peak_rank Weeks on board
This_week_rank
1                    NaN         NaN            NaN       NaN            NaN
2                    NaN         NaN            NaN       NaN            NaN
3                    NaN         NaN            NaN       NaN            NaN
4                    NaN         NaN            NaN       NaN            NaN
5                    NaN         NaN            NaN       NaN            NaN
...                  ...         ...            ...       ...            ...
96                   NaN         NaN            NaN       NaN            NaN
97                   NaN         NaN            NaN       NaN            NaN
98                   NaN         NaN            NaN       NaN            NaN
99                   NaN         NaN            NaN       NaN            NaN
100                  NaN         NaN            NaN       NaN            NaN

[100 rows x 5 columns]

In [57]:
driver.close()

# 7. Scrape the details of Data science recruiters from naukri.com.

Url = https://www.naukri.com/

You have to find the following details: A) Name B) Designation C) Company D) Skills they hire for E) Location

In [13]:
driver = webdriver.Chrome(ChromeDriverManager().install())

# Getting the webpage of mentioned url 
url=(' https://www.naukri.com/hr-recruiters-consultants')
    
driver.get(url)
driver.maximize_window()
time.sleep(2)

NameError: name 'ChromeDriverManager' is not defined

In [149]:
#Fetching urls to navigate recruiter page
recruiter = driver.find_element(By.XPATH,'//a[@title="Search Jobs"]')
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)

In [150]:
#Fetching urls to navigate recruiter page
recruiter = driver.find_element(By.XPATH,'/html/body/div[1]/div/ul/li[2]/a')
page_url = recruiter.get_attribute("href")

driver.get(page_url)
time.sleep(3)

In [151]:
# Fetching search button, sending keys and clicking on it
search = driver.find_element(By.XPATH,"//div[@class='inpWrap']//input") 
search.send_keys("Data science ")           
btn = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[1]/div[1]/form/div[1]/button').click()     
time.sleep(3)

In [152]:
#Creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []

In [153]:
#Scraping data of Names
for i in driver.find_elements(By.XPATH,"//span[@class='fl ellipsis']"):
    Name.append(i.text)
time.sleep(3)

#Scraping data of Designation
for i in driver.find_elements(By.XPATH,"//span[@class='ellipsis clr']"):
    Designation.append(i.text)
    
#Scraping data of company name
for i in driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]/a[2]"):
    Company.append(i.text)

#Scraping data of locations
for i in driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]//span"):
    Location.append(i.text)
time.sleep(3)

In [154]:
print(len(Name),len(Designation),len(Company),len(Location))

50 50 50 148

In [155]:
# Creating dataframe for scraped data
Naukri=pd.DataFrame({})
Naukri['Name'] = Name
Naukri['Designation'] = Designation
Naukri['Company'] = Company
Naukri['Location'] = Location[:50]
Naukri

,Name,Designation,Company,Location
0,Aakash Harit,HR Manager,Data Science Network,Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,MARSIAN Technologies LLP
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Company HR
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Pune
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Anik Agrawal
10,Kalpana Dumpala,Executive Hiring,Innominds Software,Company Recruiter
11,Mubarak,Company HR,MoneyTap,Ahmedabad
12,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,subhas patel
13,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Founder CEO
14,Vaishnavi Kudalkar,HR Executive,Codeachive learning,UK - (london)
15,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Abhishek - Only Analytics Hiring - India and
16,Kapil Devang,HR Manager,BISP Solutions,Recruitment Lead Consultant
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Vadodara / Baroda
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Institute for Financial Management and Resear
19,Manisha Yadav,HR Executive,Easi Tax,Programme Manager
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Chennai
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Balu Ramesh
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,HR Administrator
23,Rithika dadwal,HR Recruiter,Affine Analytics,Trivandrum
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Asif Lucknowi
25,Shaun Rao,Manager Human Resources,Exela Technologies,Director
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Indore
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,InstaFinancials
28,kumar,Proprietor,trainin,Human Resource
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,Bengaluru / Bangalore
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Kalpana Dumpala
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,Executive Hiring
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Hyderabad / Secunderabad
33,Avodha,Business Development Associate,Nikitha Palaparthi,Mubarak
34,Priya Khare,Senior Manager,Independent Consultant,Company HR
35,Amit Sharma,Consultant,ASCO consulting,Bengaluru / Bangalore
36,Kanan,senior technology instructor,NY INST,Kushal Rastogi
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Company HR
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,Mumbai
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,Mahesh Babu Channa
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,HR Team Lead
41,Ankit Sinha,Head Analytics,Suntech Global,Hyderabad / Secunderabad
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Vaishnavi Kudalkar
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,HR Executive
44,Ashwini,Director Global Delivery,MRP Advisers,Mumbai
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Priyanka Akiri
46,Rajani Nagaraj,HR Manager,WildJasmine,HR Manager
47,ROHIT Kumar,Architect,LNT Private Limited,Hyderabad
48,Amir Chowdhury,Managing Partner,Granular.ai,Kapil Devang
49,SREEDHAR,Recruitment Consultant,JOBSMILL BUSINESS SOLUTIONS PRIVATE LIMITED,HR Manager

In [156]:
driver.close()

# 8. Scrape the details of Highest selling novels.

Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey%02compare/

You have to find the following details: A) Book name B) Author name C) Volumes sold D) Publisher E) Genre

In [6]:
driver = webdriver.Chrome(ChromeDriverManager().install())

# Getting the webpage of mentioned url 
url=('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/')
    
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [7]:
#Creating empty list
Bookname = []
Authorname = []
Volumessold = []
Publisher = []
Genre = []

In [8]:
#scraping book names data
for i in driver.find_elements(By.XPATH,"//tbody//tr/td[2]"):
    Bookname.append(i.text)
    
#Scraping author names data
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Authorname.append(i.text)
    except NoSuchElementException:
        Authorname.append('-')
time.sleep(1)

#Scraping data of volumes sold
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[4]"):
    Volumessold.append(i.text)
    
#Scraping data of publisher names
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[5]"):
    Publisher.append(i.text)
    
#Scraping data of genre
for i in driver.find_elements(By.XPATH,"//tbody/tr/td[6]"):
    Genre.append(i.text)

In [9]:
#Creating dataframe for scraped data
Novels=pd.DataFrame({})
Novels['Book Name'] = Bookname
Novels['Author'] = Authorname
Novels['Volume sold'] = Volumessold
Novels['Publisher'] = Publisher
Novels['Genre'] = Genre
Novels

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [10]:
driver.close()

# 9. Scrape the details most watched tv series of all time from imdb.com.

Url = https://www.imdb.com/list/ls095964455/

You have to find the following details: A) Name B) Year span C) Genre D) Run time E) Ratings F) Votes

In [11]:
driver = webdriver.Chrome(ChromeDriverManager().install())

# Getting the webpage of mentioned url 
url=(' https://www.imdb.com/list/ls095964455/')
    
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [12]:
#Creating empty lists.
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

In [13]:
#Scraping data of Names
for i in driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a"):
    Name.append(i.text)
    
#Scraping data of Year span
for i in driver.find_elements(By.XPATH,"//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)
    
#Scraping data of Run time
for i in driver.find_elements(By.XPATH,"//span[@class='runtime']"):
    Run_time.append(i.text)
    
#Scraping data of Ratings
for i in driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)
    
#Scraping data of genre
for i in driver.find_elements(By.XPATH,"//span[@class='genre']"):
    Genre.append(i.text)
    
#Scraping data of votes
for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text)

In [14]:
# Creating dataframe for scraped data
TVseries=pd.DataFrame({})
TVseries['Name'] = Name
TVseries['Year Span'] = Year_span
TVseries['Genre'] = Genre
TVseries['Run Time'] = Run_time
TVseries['Ratings'] = Ratings
TVseries['Votes'] = Votes
TVseries

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,091,213"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,180,694"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"989,586"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"292,981"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"252,149"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"50,207"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"61,517"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"198,515"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"41,591"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"245,416"

In [ ]:
driver.close()

# 10. Details of Datasets from UCI machine learning repositories.

Url = https://archive.ics.uci.edu/

You have to find the following details: A) Dataset name B) Data type C) Task D) Attribute type E) No of instances F) No of attribute G) Year

In [15]:
driver = webdriver.Chrome(ChromeDriverManager().install())

# Getting the webpage of mentioned url 
url=('https://archive.ics.uci.edu/')
    
driver.get(url)
driver.maximize_window()
time.sleep(2)

In [16]:
# Finding view all dataset button from the webpage
viewall_dataset = driver.find_element(By.XPATH,"//tbody[1]//tr/td[2]/span[2]/a")    
page_url = viewall_dataset.get_attribute("href")
driver.get(page_url)

In [17]:
# Fetching page urls of all datasets 
view_list = driver.find_element(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")  
list_url = view_list.get_attribute("href")           
driver.get(list_url)

In [18]:
# Fetching urls for each dataset
dataset_url = driver.find_elements(By.XPATH,"//p[@class='normal']//b/a")    

urls = []     
for i in dataset_url:
    urls.append(i.get_attribute("href"))

In [19]:
#Creating empty lists
Dataset_name = []
Data_type = []
Task = []
Attribute_type = []
No_of_instances = []
No_of_attributes = []
Year = []

In [20]:
for i in urls:
    driver.get(i)
    time.sleep(2)
    
    #Scraping Dataset name
    try: 
        dataset_name = driver.find_element(By.XPATH,"//span[@class='heading']")
        Dataset_name.append(dataset_name.text)
    except NoSuchElementException:
        Dataset_name.append('-')
    
    
    #Scraping data type
    try:
        data_type = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr/td[2]")
        if data_type.text == "N/A": raise NoSuchElementException
        Data_type.append(data_type.text)
    except NoSuchElementException:
        Data_type.append('-')
    
    
    #scraping Task
    try:
        task = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[3]/td[2]")
        if task.text == "N/A": raise NoSuchElementException
        Task.append(task.text)
    except NoSuchElementException:
        Task.append('-')
    
    
    # Scraping Attribute type
    try:
        attribute_type = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[2]")
        if attribute_type.text == "N/A": raise NoSuchElementException
        Attribute_type.append(attribute_type.text)
    except NoSuchElementException:
        Attribute_type.append('-')
    
    
    # Scraping No of instances
    try:
        instances = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr/td[4]")
        if instances.text == "N/A": raise NoSuchElementException
        No_of_instances.append(instances.text)
    except NoSuchElementException:
        No_of_instances.append('-')
    
    
    # Scraping No of attributes
    try:
        attribute = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[4]")
        if attribute.text == "N/A": raise NoSuchElementException
        No_of_attributes.append(attribute.text)
    except NoSuchElementException:
        No_of_attributes.append('-')
    
    
    # Scraping year
    try:
        year = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[6]")
        if year.text == "N/A": raise NoSuchElementException
        Year.append(year.text[:4])
    except NoSuchElementException:
        Year.append('-')

In [21]:
# Creating dataframe 

ML=pd.DataFrame({})
ML['Data Name'] = Dataset_name[:622]
ML['Data Type'] = Data_type[:622]
ML['Task'] = Task[:622]
ML['Attribute type'] = Attribute_type[:622]
ML['No of instance'] = No_of_instances[:622]
ML['No of attributes'] = No_of_attributes[:622]
ML['Year'] = Year[:622]
ML

,Data Name,Data Type,Task,Attribute type,No of instance,No of attributes,Year
0,2.4 GHZ Indoor Channel Measurements Data Set,Multivariate,Classification,Real,7840,5,2018
1,"3D Road Network (North Jutland, Denmark) Data Set","Sequential, Text","Regression, Clustering",Real,434874,4,2013
2,3W dataset Data Set,"Multivariate, Time-Series","Classification, Clustering","Integer, Real",1984,8,2019
3,9mers from cullpdb Data Set,Sequential,"Classification, Regression",Real,158716,4,2021
4,: Simulated Data set of Iraqi tourism places D...,Multivariate,"Classification, Clustering",-,232,16,2020
...,...,...,...,...,...,...,...
617,Youtube cookery channels viewers comments in H...,"Multivariate, Text",Classification,-,9800,3,2019
618,YouTube Multiview Video Games Dataset Data Set,"Multivariate, Text","Classification, Clustering","Integer, Real",120000,1000000,2013
619,YouTube Spam Collection Data Set,Text,Classification,-,1956,5,2017
620,Z-Alizadeh Sani Data Set,-,Classification,"Integer, Real",303,56,2017
621,Zoo Data Set,Multivariate,Classification,"Categorical, Integer",101,17,1990

In [22]:
driver.close()